apiVersion: v1
kind: Pod
metadata:
  name: grilledcheese
  labels:
    cheeseType: "american"
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: cheeseType
                operator: Exists
          topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "nutType"
            operator: In
            values: 
            - "peanut"
            - "almond"
        topologyKey: kubernetes.io/hostname
  containers:
  - name: grilledcheese
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
  terminationGracePeriodSeconds: 0
  restartPolicy: Always
