apiVersion: v1
kind: Pod
metadata:
  name: deathstar
  labels:
    app: galacticEmpire
spec:
  containers:
  - name: tarkin
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
    resources:
      limits:
        cpu: "10"
        memory: "16Gi"
  restartPolicy: Always
