apiVersion: v1
kind: Pod
metadata:
  name: millenium-falcon
  labels:
    app: rebelAlliance
spec:
  containers:
  - name: han
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
  - name: chewy
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
  restartPolicy: Always
