---
apiVersion: v1
kind: Pod
metadata:
  name: chimera
  labels:
    app: galacticEmpire
spec:
  containers:
  - name: thrawn
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
    resources:
      requests:
        cpu: ".5"
        memory: "512Mi"
      limits:
        cpu: ".75"
        memory: "768Mi"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: hydra
  labels:
    app: galacticEmpire
spec:
  containers:
  - name: daala
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
    resources:
      requests:
        cpu: ".5"
        memory: "512Mi"
      limits:
        cpu: ".75"
        memory: "768Mi"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: tyrant
  labels:
    app: galacticEmpire
spec:
  containers:
  - name: lennox
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
    resources:
      requests:
        cpu: ".375"
        memory: "368Mi"
      limits:
        cpu: ".5"
        memory: "512Mi"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: accuser
  labels:
    app: galacticEmpire
spec:
  containers:
  - name: vader
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
  restartPolicy: Always
