apiVersion: v1
kind: Pod
metadata:
  name: x-wing
  labels:
    app: rebelAlliance
spec:
  containers:
  - name: luke
    image: fedora:29
    command: ["sleep"]
    args: ["3600"]
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"
  restartPolicy: Always
